import { writeFile } from "node:fs/promises";
import { stringify } from "smol-toml";
import type { Lockfile } from "./schema.js";

const HEADER = "# Auto-generated by dotagents. Do not edit.\n";

/**
 * Write an agents.lock file.
 * Skills are sorted alphabetically for deterministic output.
 */
export async function writeLockfile(
  filePath: string,
  lockfile: Lockfile,
): Promise<void> {
  // Sort skills by name for deterministic output
  const sortedSkills: Record<string, unknown> = {};
  for (const name of Object.keys(lockfile.skills).sort()) {
    sortedSkills[name] = lockfile.skills[name];
  }

  const toml = stringify({ version: lockfile.version, skills: sortedSkills });
  await writeFile(filePath, HEADER + toml + "\n", "utf-8");
}
