import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtemp, rm, readFile, writeFile, lstat, readdir } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { existsSync } from "node:fs";
import { runInit, InitError } from "./init.js";
import { loadConfig } from "../../config/loader.js";

describe("runInit", () => {
  let dir: string;

  beforeEach(async () => {
    dir = await mkdtemp(join(tmpdir(), "dotagents-init-test-"));
  });

  afterEach(async () => {
    await rm(dir, { recursive: true });
  });

  it("creates agents.toml in project root", async () => {
    await runInit({ projectRoot: dir });

    const config = await loadConfig(join(dir, "agents.toml"));
    expect(config.version).toBe(1);
    expect(config.skills).toEqual({});
  });

  it("creates .agents/skills/ directory", async () => {
    await runInit({ projectRoot: dir });

    const stat = await lstat(join(dir, ".agents", "skills"));
    expect(stat.isDirectory()).toBe(true);
  });

  it("creates .agents/.gitignore", async () => {
    await runInit({ projectRoot: dir });

    const content = await readFile(join(dir, ".agents", ".gitignore"), "utf-8");
    expect(content).toContain("Auto-generated by dotagents");
  });

  it("throws InitError if agents.toml exists without --force", async () => {
    await writeFile(join(dir, "agents.toml"), "version = 1\n[skills]\n");

    await expect(runInit({ projectRoot: dir })).rejects.toThrow(InitError);
    await expect(runInit({ projectRoot: dir })).rejects.toThrow(
      "agents.toml already exists",
    );
  });

  it("overwrites agents.toml with --force", async () => {
    await writeFile(join(dir, "agents.toml"), "garbage content");

    await runInit({ projectRoot: dir, force: true });

    const config = await loadConfig(join(dir, "agents.toml"));
    expect(config.version).toBe(1);
  });

  it("is idempotent with --force", async () => {
    await runInit({ projectRoot: dir });
    await runInit({ projectRoot: dir, force: true });

    const config = await loadConfig(join(dir, "agents.toml"));
    expect(config.version).toBe(1);
    expect(existsSync(join(dir, ".agents", "skills"))).toBe(true);
  });

  it("does not create symlinks with default config", async () => {
    await runInit({ projectRoot: dir });

    // Default config has no symlinks configured, so .claude should not exist
    expect(existsSync(join(dir, ".claude"))).toBe(false);
  });

  it("creates all expected files and directories", async () => {
    await runInit({ projectRoot: dir });

    expect(existsSync(join(dir, "agents.toml"))).toBe(true);
    expect(existsSync(join(dir, ".agents"))).toBe(true);
    expect(existsSync(join(dir, ".agents", "skills"))).toBe(true);
    expect(existsSync(join(dir, ".agents", ".gitignore"))).toBe(true);
  });

  it("preserves existing .agents/skills/ contents", async () => {
    const { mkdir, writeFile: wf } = await import("node:fs/promises");
    await mkdir(join(dir, ".agents", "skills", "my-skill"), { recursive: true });
    await wf(join(dir, ".agents", "skills", "my-skill", "SKILL.md"), "# test");

    await runInit({ projectRoot: dir });

    const entries = await readdir(join(dir, ".agents", "skills"));
    expect(entries).toContain("my-skill");
  });
});
