import { writeFile } from "node:fs/promises";
import { join } from "node:path";

const HEADER = `# Auto-generated by dotagents. Do not edit.
# Managed skills (installed by dotagents)`;

/**
 * Generate .agents/.gitignore listing managed skill directories.
 * Skills with path: sources are also gitignored since they're installed by dotagents.
 */
export async function writeAgentsGitignore(
  agentsDir: string,
  managedSkillNames: string[],
): Promise<void> {
  const lines = [HEADER];
  for (const name of managedSkillNames.sort()) {
    lines.push(`/skills/${name}/`);
  }
  lines.push(""); // trailing newline

  await writeFile(join(agentsDir, ".gitignore"), lines.join("\n"), "utf-8");
}
