import { rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

const HEADER = `# Auto-generated by dotagents. Do not edit.
# Managed skills (installed by dotagents)`;

/**
 * Generate .agents/.gitignore listing managed skill directories.
 * Skills with path: sources are also gitignored since they're installed by dotagents.
 */
export async function writeAgentsGitignore(
  agentsDir: string,
  managedSkillNames: string[],
): Promise<void> {
  const lines = [HEADER];
  for (const name of managedSkillNames.sort()) {
    lines.push(`/skills/${name}/`);
  }
  lines.push(""); // trailing newline

  await writeFile(join(agentsDir, ".gitignore"), lines.join("\n"), "utf-8");
}

/**
 * Remove .agents/.gitignore if it exists.
 */
export async function removeAgentsGitignore(agentsDir: string): Promise<void> {
  const gitignorePath = join(agentsDir, ".gitignore");
  if (existsSync(gitignorePath)) {
    await rm(gitignorePath);
  }
}

/**
 * Create or remove .agents/.gitignore based on the gitignore config option.
 * When gitignore is true, generates the gitignore listing managed skills.
 * When gitignore is false, removes the gitignore file if it exists.
 */
export async function updateAgentsGitignore(
  agentsDir: string,
  gitignore: boolean,
  managedSkillNames: string[],
): Promise<void> {
  if (gitignore) {
    await writeAgentsGitignore(agentsDir, managedSkillNames);
  } else {
    await removeAgentsGitignore(agentsDir);
  }
}
