import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtemp, readFile, rm, mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { existsSync } from "node:fs";
import { writeAgentsGitignore, removeAgentsGitignore, updateAgentsGitignore } from "./writer.js";

describe("writeAgentsGitignore", () => {
  let dir: string;

  beforeEach(async () => {
    dir = await mkdtemp(join(tmpdir(), "dotagents-test-"));
    await mkdir(join(dir, ".agents"), { recursive: true });
  });

  afterEach(async () => {
    await rm(dir, { recursive: true });
  });

  it("writes header with no managed skills", async () => {
    const agentsDir = join(dir, ".agents");
    await writeAgentsGitignore(agentsDir, []);

    const content = await readFile(join(agentsDir, ".gitignore"), "utf-8");
    expect(content).toContain("Auto-generated by dotagents");
    expect(content.split("\n").filter((l) => l.startsWith("/skills/"))).toHaveLength(0);
  });

  it("lists managed skill directories", async () => {
    const agentsDir = join(dir, ".agents");
    await writeAgentsGitignore(agentsDir, ["pdf", "find-bugs", "code-review"]);

    const content = await readFile(join(agentsDir, ".gitignore"), "utf-8");
    expect(content).toContain("/skills/code-review/");
    expect(content).toContain("/skills/find-bugs/");
    expect(content).toContain("/skills/pdf/");
  });

  it("sorts skill names alphabetically", async () => {
    const agentsDir = join(dir, ".agents");
    await writeAgentsGitignore(agentsDir, ["zebra", "alpha", "middle"]);

    const content = await readFile(join(agentsDir, ".gitignore"), "utf-8");
    const lines = content.split("\n").filter((l) => l.startsWith("/skills/"));
    expect(lines).toEqual([
      "/skills/alpha/",
      "/skills/middle/",
      "/skills/zebra/",
    ]);
  });

  it("overwrites existing gitignore", async () => {
    const agentsDir = join(dir, ".agents");
    await writeAgentsGitignore(agentsDir, ["old-skill"]);
    await writeAgentsGitignore(agentsDir, ["new-skill"]);

    const content = await readFile(join(agentsDir, ".gitignore"), "utf-8");
    expect(content).not.toContain("old-skill");
    expect(content).toContain("new-skill");
  });
});

describe("removeAgentsGitignore", () => {
  let dir: string;

  beforeEach(async () => {
    dir = await mkdtemp(join(tmpdir(), "dotagents-test-"));
    await mkdir(join(dir, ".agents"), { recursive: true });
  });

  afterEach(async () => {
    await rm(dir, { recursive: true });
  });

  it("removes existing .gitignore", async () => {
    const agentsDir = join(dir, ".agents");
    await writeFile(join(agentsDir, ".gitignore"), "some content");
    await removeAgentsGitignore(agentsDir);
    expect(existsSync(join(agentsDir, ".gitignore"))).toBe(false);
  });

  it("is a no-op when .gitignore does not exist", async () => {
    const agentsDir = join(dir, ".agents");
    await removeAgentsGitignore(agentsDir);
    expect(existsSync(join(agentsDir, ".gitignore"))).toBe(false);
  });
});

describe("updateAgentsGitignore", () => {
  let dir: string;

  beforeEach(async () => {
    dir = await mkdtemp(join(tmpdir(), "dotagents-test-"));
    await mkdir(join(dir, ".agents"), { recursive: true });
  });

  afterEach(async () => {
    await rm(dir, { recursive: true });
  });

  it("creates .gitignore when gitignore is true", async () => {
    const agentsDir = join(dir, ".agents");
    await updateAgentsGitignore(agentsDir, true, ["my-skill"]);

    const content = await readFile(join(agentsDir, ".gitignore"), "utf-8");
    expect(content).toContain("/skills/my-skill/");
  });

  it("removes .gitignore when gitignore is false", async () => {
    const agentsDir = join(dir, ".agents");
    await writeFile(join(agentsDir, ".gitignore"), "existing content");
    await updateAgentsGitignore(agentsDir, false, ["my-skill"]);
    expect(existsSync(join(agentsDir, ".gitignore"))).toBe(false);
  });

  it("does not create .gitignore when gitignore is false", async () => {
    const agentsDir = join(dir, ".agents");
    await updateAgentsGitignore(agentsDir, false, ["my-skill"]);
    expect(existsSync(join(agentsDir, ".gitignore"))).toBe(false);
  });
});
