import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtemp, readFile, rm, mkdir } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { writeAgentsGitignore } from "./writer.js";

describe("writeAgentsGitignore", () => {
  let dir: string;

  beforeEach(async () => {
    dir = await mkdtemp(join(tmpdir(), "dotagents-test-"));
    await mkdir(join(dir, ".agents"), { recursive: true });
  });

  afterEach(async () => {
    await rm(dir, { recursive: true });
  });

  it("writes header with no managed skills", async () => {
    const agentsDir = join(dir, ".agents");
    await writeAgentsGitignore(agentsDir, []);

    const content = await readFile(join(agentsDir, ".gitignore"), "utf-8");
    expect(content).toContain("Auto-generated by dotagents");
    expect(content.split("\n").filter((l) => l.startsWith("/skills/"))).toHaveLength(0);
  });

  it("lists managed skill directories", async () => {
    const agentsDir = join(dir, ".agents");
    await writeAgentsGitignore(agentsDir, ["pdf", "find-bugs", "code-review"]);

    const content = await readFile(join(agentsDir, ".gitignore"), "utf-8");
    expect(content).toContain("/skills/code-review/");
    expect(content).toContain("/skills/find-bugs/");
    expect(content).toContain("/skills/pdf/");
  });

  it("sorts skill names alphabetically", async () => {
    const agentsDir = join(dir, ".agents");
    await writeAgentsGitignore(agentsDir, ["zebra", "alpha", "middle"]);

    const content = await readFile(join(agentsDir, ".gitignore"), "utf-8");
    const lines = content.split("\n").filter((l) => l.startsWith("/skills/"));
    expect(lines).toEqual([
      "/skills/alpha/",
      "/skills/middle/",
      "/skills/zebra/",
    ]);
  });

  it("overwrites existing gitignore", async () => {
    const agentsDir = join(dir, ".agents");
    await writeAgentsGitignore(agentsDir, ["old-skill"]);
    await writeAgentsGitignore(agentsDir, ["new-skill"]);

    const content = await readFile(join(agentsDir, ".gitignore"), "utf-8");
    expect(content).not.toContain("old-skill");
    expect(content).toContain("new-skill");
  });
});
